DROP DATABASE IF EXISTS retro;
CREATE DATABASE retro;

use retro;
DROP TABLE IF EXISTS Compte;
CREATE TABLE Compte(ID INT,Client_ID INT, Grade VARCHAR(20));
DROP TABLE IF EXISTS Client;
CREATE TABLE Client(ID INT,Nom VARCHAR(20));
DROP TABLE IF EXISTS Produits;
CREATE TABLE Produits (ID INT, Compte_ID INT, Nom VARCHAR (20),Quantité VARCHAR(4));
DROP TABLE IF EXISTS Panier;
CREATE TABLE Panier(ID INT, Produit_ID INT, Quantité VARCHAR(4));
DROP TABLE IF EXISTS Prix;
CREATE TABLE Prix (ID INT, Produit_ID INT, Nombre VARCHAR(5));
DROP TABLE IF EXISTS Recherche;
CREATE TABLE Recherche (ID INT,Produit_ID INT,Nom VARCHAR(20));
DROP TABLE IF EXISTS Ville;
CREATE TABLE Ville (ID INT,Nom VARCHAR (20));
DROP TABLE IF EXISTS Boutique;
CREATE TABLE Boutique (ID INT, Ville_ID INT, Nom VARCHAR(20));
DROP TABLE IF EXISTS Commande;
CREATE TABLE Commande(ID INT, Panier_ID INT, Boutique_ID INT);


ALTER TABLE Compte
ADD PRIMARY KEY (ID);
ALTER TABLE Produits
ADD PRIMARY KEY (ID);
ALTER TABLE Panier
ADD PRIMARY KEY (ID);
ALTER TABLE Client
ADD PRIMARY KEY (ID);
ALTER TABLE Prix
ADD PRIMARY KEY (ID);
ALTER TABLE Recherche
ADD PRIMARY KEY (ID);
ALTER TABLE Ville
ADD PRIMARY KEY (ID);
ALTER TABLE Boutique
ADD PRIMARY KEY (ID);
ALTER TABLE Commande
ADD PRIMARY KEY (ID);


ALTER TABLE Compte ADD FOREIGN KEY (Client_ID) REFERENCES Client (ID);
ALTER TABLE Boutique ADD FOREIGN KEY (Ville_ID) REFERENCES Ville (ID);
ALTER TABLE Prix  ADD FOREIGN KEY(Produit_ID) REFERENCES Produits(ID);
ALTER TABLE Commande ADD FOREIGN KEY(Panier_ID) REFERENCES Panier(ID);
ALTER TABLE Commande ADD FOREIGN KEY(Boutique_ID) REFERENCES Boutique(ID);
ALTER TABLE Recherche ADD FOREIGN KEY(Produit_ID) REFERENCES Produits(ID);
ALTER TABLE Produits ADD FOREIGN KEY(Compte_ID) REFERENCES Compte(ID);
ALTER TABLE Panier ADD FOREIGN KEY(Produit_ID) REFERENCES Produits(ID);


SELECT * FROM retro
INNER JOIN Client
ON Compte.Client_ID=Client.ID;
SELECT * FROM retro
INNER JOIN Prix
ON Prix.Produit_ID=Produits.ID;
SELECT * FROM retro
INNER JOIN Boutique
ON Boutique.Ville_ID=Ville.ID;
SELECT * FROM retro
INNER JOIN Commande
ON Commande.Panier_ID=Panier.ID;
SELECT * FROM retro
INNER JOIN Commande
ON Commande.Boutique_ID=Boutique.ID;
SELECT * FROM retro
INNER JOIN Recherche
ON Recherche.Produit_ID=Produits.ID;
SELECT * FROM retro
INNER JOIN Produits
ON Produits.Compte_ID=Compte.ID;
SELECT * FROM retro
INNER JOIN Panier
ON Panier.Produit_ID=Produits.ID;