DROP DATABASE IF EXISTS retro;
CREATE DATABASE retro;

use retro;
DROP TABLE IF EXISTS Compte;
CREATE TABLE Compte(ID INT,Utilisateur_ID INT, Grade VARCHAR(20));
DROP TABLE IF EXISTS Utilisateur;
CREATE TABLE Utilisateur(ID INT,Pseudo VARCHAR(20),Email VARCHAR(30),password VARCHAR(100));
DROP TABLE IF EXISTS Produits;
CREATE TABLE Produits (ID INT, Prix_ID INT, Nom VARCHAR (20),Catégorie VARCHAR(30));
DROP TABLE IF EXISTS Panier;
CREATE TABLE Panier(ID INT, Produit_ID INT, Quantité VARCHAR(4));
DROP TABLE IF EXISTS Prix;
CREATE TABLE Prix (ID INT, Produit_ID INT, Nombre VARCHAR(5));
DROP TABLE IF EXISTS Recherche;
CREATE TABLE Recherche (ID INT,Produit_ID INT,Nom VARCHAR(20));
DROP TABLE IF EXISTS Ville;
CREATE TABLE Ville (ID INT,Nom VARCHAR (20));
DROP TABLE IF EXISTS Boutique;
CREATE TABLE Boutique (ID INT, Ville_ID INT, Nom VARCHAR(20));
DROP TABLE IF EXISTS Commande;
CREATE TABLE Commande(ID INT, Panier_ID INT, Boutique_ID INT);


ALTER TABLE Compte
ADD PRIMARY KEY (ID);
ALTER TABLE Produits
ADD PRIMARY KEY (ID);
ALTER TABLE Panier
ADD PRIMARY KEY (ID);
ALTER TABLE Utilisateur
ADD PRIMARY KEY (ID);
ALTER TABLE Prix
ADD PRIMARY KEY (ID);
ALTER TABLE Recherche
ADD PRIMARY KEY (ID);
ALTER TABLE Ville
ADD PRIMARY KEY (ID);
ALTER TABLE Boutique
ADD PRIMARY KEY (ID);
ALTER TABLE Commande
ADD PRIMARY KEY (ID);


SELECT * FROM Compte
INNER JOIN Utilisateur
ON Compte.Utilisateur_ID=Utilisateur.ID;
SELECT * FROM Produits
INNER JOIN Prix
ON Prix.Produit_ID=Produits.ID;
SELECT * FROM Ville
INNER JOIN Boutique
ON Boutique.Ville_ID=Ville.ID;
SELECT * FROM Panier
INNER JOIN Commande
ON Commande.Panier_ID=Panier.ID;
SELECT * FROM Boutique
INNER JOIN Commande
ON Commande.Boutique_ID=Boutique.ID;
SELECT * FROM Produits
INNER JOIN Recherche
ON Recherche.Produit_ID=Produits.ID;

SELECT * FROM Produits
INNER JOIN Panier
ON Panier.Produit_ID=Produits.ID;